// constants.js — Shared constants for the entire extension

export const BTT_VERSION = '1.0.0';
export const BTT_STORAGE_PREFIX = 'btt_';
export const TOOLKIT_THEME_STORAGE_KEY = 'bttToolkitTheme';
export const FORUM_THEME_STORAGE_KEY = 'bttForumTheme';

export const DEFAULT_FORUM_CUSTOM_COLORS = {
  pageBg: '#f6f6f6',
  cardBg: '#ffffff',
  text: '#222222',
  mutedText: '#666666',
  border: '#cccccc',
  divider: '#dddddd',
  link: '#3366cc',
  linkVisited: '#663399',
  linkHover: '#cc6600',
  linkActive: '#ff6600',
  categoryHeaderBg: '#e5e5e5',
  categoryHeaderText: '#111111',
  boardHeaderBg: '#d8d8d8',
  boardHeaderText: '#111111',
  tableHeaderBg: '#eeeeee',
  tableHeaderText: '#111111',
  postBg: '#ffffff',
  postAltBg: '#f8f8f8',
  postTitle: '#222222',
  postMeta: '#666666',
  signatureText: '#555555',
  quoteBg: '#f9f9f9',
  quoteText: '#222222',
  quoteBorder: '#bbbbbb',
  codeBg: '#eeeeee',
  codeText: '#222222',
  codeBorder: '#bbbbbb',
  buttonBg: '#dddddd',
  buttonText: '#111111',
  buttonHoverBg: '#cccccc',
  inputBg: '#ffffff',
  inputText: '#111111',
  inputBorder: '#aaaaaa',
  selectedBg: '#cce5ff',
  selectedText: '#000000',
  newPostHighlight: '#fff4cc',
  warning: '#c98200',
  success: '#1f8f3a',
  danger: '#cc3333',
  info: '#337ab7',
  merit: '#008000',
  trustPositive: '#008000',
  trustNeutral: '#666666',
  trustNegative: '#cc0000',
  dtBadge: '#d97706',
  dt1Badge: '#2563eb',
  dt2Badge: '#7c3aed',
  notificationBadge: '#dc2626',
  tooltipBg: '#111111',
  tooltipText: '#ffffff',
};

export const THEME_DEFS = {
  dark: {
    name: 'Dark Mode',
    values: {
      bg: '#0f1117',
      surface: '#1a1d23',
      surface2: '#1e2025',
      text: '#e5e7eb',
      mutedText: '#9ca3af',
      border: '#2d3340',
      primary: '#3b82f6',
      primaryHover: '#60a5fa',
      accent: '#f7931a',
      success: '#22c55e',
      warning: '#f59e0b',
      danger: '#ef4444',
      link: '#60a5fa',
      inputBg: '#1e2025',
      buttonBg: '#252a35',
      buttonText: '#ffffff',
      previewBg: '#ffffff',
      previewText: '#111827',
    },
  },
  light: {
    name: 'Classic Light',
    values: {
      bg: '#f3f4f6',
      surface: '#ffffff',
      surface2: '#f9fafb',
      text: '#111827',
      mutedText: '#6b7280',
      border: '#d1d5db',
      primary: '#2563eb',
      primaryHover: '#1d4ed8',
      accent: '#f7931a',
      success: '#16a34a',
      warning: '#d97706',
      danger: '#dc2626',
      link: '#1d4ed8',
      inputBg: '#ffffff',
      buttonBg: '#eef2ff',
      buttonText: '#111827',
      previewBg: '#ffffff',
      previewText: '#111827',
    },
  },
  bitcoin: {
    name: 'Bitcoin Orange',
    values: {
      bg: '#17120b',
      surface: '#24180d',
      surface2: '#302012',
      text: '#fff7ed',
      mutedText: '#f1c38a',
      border: '#5b3414',
      primary: '#f7931a',
      primaryHover: '#ffad3b',
      accent: '#facc15',
      success: '#22c55e',
      warning: '#f59e0b',
      danger: '#ef4444',
      link: '#fbbf24',
      inputBg: '#1f160c',
      buttonBg: '#3a2410',
      buttonText: '#fff7ed',
      previewBg: '#fff8ef',
      previewText: '#24180d',
    },
  },
  'forum-gray': {
    name: 'Forum Gray',
    values: {
      bg: '#d8dbe2',
      surface: '#eef0f4',
      surface2: '#ffffff',
      text: '#1f2937',
      mutedText: '#4b5563',
      border: '#aeb5c1',
      primary: '#50627a',
      primaryHover: '#3f4f63',
      accent: '#c6812d',
      success: '#15803d',
      warning: '#b45309',
      danger: '#b91c1c',
      link: '#1f5d9d',
      inputBg: '#ffffff',
      buttonBg: '#e5e7eb',
      buttonText: '#1f2937',
      previewBg: '#ffffff',
      previewText: '#111827',
    },
  },
  'soft-blue': {
    name: 'Soft Blue',
    values: {
      bg: '#eef6ff',
      surface: '#f8fbff',
      surface2: '#ffffff',
      text: '#172033',
      mutedText: '#5d708c',
      border: '#bfd5ee',
      primary: '#2f80ed',
      primaryHover: '#1c64d1',
      accent: '#f7931a',
      success: '#169b62',
      warning: '#c98216',
      danger: '#d14343',
      link: '#1f65c1',
      inputBg: '#ffffff',
      buttonBg: '#e5f0ff',
      buttonText: '#172033',
      previewBg: '#ffffff',
      previewText: '#172033',
    },
  },
  sepia: {
    name: 'Sepia Reading Mode',
    values: {
      bg: '#f4ecd8',
      surface: '#fbf4e3',
      surface2: '#fff9ea',
      text: '#33291c',
      mutedText: '#7a6548',
      border: '#d2bd94',
      primary: '#8f5b22',
      primaryHover: '#704616',
      accent: '#b7791f',
      success: '#2f855a',
      warning: '#b7791f',
      danger: '#b83232',
      link: '#6b4e16',
      inputBg: '#fffaf0',
      buttonBg: '#ead9b8',
      buttonText: '#33291c',
      previewBg: '#fffaf0',
      previewText: '#33291c',
    },
  },
  'high-contrast': {
    name: 'High Contrast',
    values: {
      bg: '#000000',
      surface: '#000000',
      surface2: '#111111',
      text: '#ffffff',
      mutedText: '#f5f5f5',
      border: '#ffffff',
      primary: '#ffff00',
      primaryHover: '#ffffff',
      accent: '#00ffff',
      success: '#00ff66',
      warning: '#ffff00',
      danger: '#ff4d4d',
      link: '#00ffff',
      inputBg: '#000000',
      buttonBg: '#222222',
      buttonText: '#ffffff',
      previewBg: '#000000',
      previewText: '#ffffff',
    },
  },
};

export const THEME_OPTIONS = Object.entries(THEME_DEFS).map(([id, theme]) => ({
  id,
  name: theme.name,
}));

export const FORUM_THEME_OPTIONS = [
  { id: 'original', name: 'Original Bitcointalk' },
  { id: 'custom', name: 'Custom Forum Theme' },
  ...THEME_OPTIONS,
];

// ── Default settings ───────────────────────────────────────────────────────
export const DEFAULT_SETTINGS = {
  enabledModules: [
    'codeCopyFixer', 'navigationBooster', 'quoteAssistant',
    'localDraftSaver', 'clipboardSafety', 'boardCleaner', 'addressHighlighter',
    'keywordAlert', 'antiPhishingLinkChecker', 'longQuoteCollapser',
    'userNotes', 'externalLinkPreview', 'imageCollapser', 'postLinkCopier',
    'trustPositionBadge',
  ],
  darkMode:             false,
  theme:                'dark',
  toolkitTheme:         'dark',
  forumTheme:           'original',
  forumCustomColors:    { ...DEFAULT_FORUM_CUSTOM_COLORS },
  dashboardDarkMode:    true,
  compactMode:          false,
  hideAvatars:          true,
  hideSignatures:       true,
  hidePersonalText:     false,
  collapseQuotes:       false,
  collapseImages:       false,
  boardCleanerDefaultsV2: true,
  clipboardProtection:  true,
  mobileEnhancer:       true,
  watchedKeywords:      [],
  userNotes:            {},
  savedDrafts:          {},
  bookmarks:            [],
  personalSnippets:     [],
  legacyScriptsEnabled: false,
  clipboardWhitelist:   [],
  ignoredUsers:         [],
  watchedUsers:         [],
  trustPositionBadgeEnabled: true,
  trustPositionBadgeShowNoDt: false,
  showNotInDt: false,
  trustPositionBadgeDebug: false,
  trustPositionBadgeSourceMode: 'custom-thread',
  trustPositionBadgeCustomThreadUrl: 'https://bitcointalk.org/index.php?topic=5584668.msg66790923#msg66790923',
  trustPositionBadgeCustomAuthor: '3727674',
  savedSnippets:        [],
  campaignProjects:     [],
  giveawayHistory:      [],
  quoteCollapseHeight:  300,
  imageCollapseHeight:  400,
  scraperDelay:         2000,
  autoSaveInterval:     5000,
};

// ── Bitcointalk rank thresholds ─────────────────────────────────────────────
// Each rank requires [posts/activity, merit (where applicable)]
// Source: Bitcointalk forum rank system
export const BTC_RANKS = [
  { name: 'Brand new member', minActivity: 0,    minMerit: 0,   color: '#aaa' },
  { name: 'Newbie',           minActivity: 1,    minMerit: 0,   color: '#aaa' },
  { name: 'Jr. Member',       minActivity: 30,   minMerit: 0,   color: '#aaa' },
  { name: 'Member',           minActivity: 120,  minMerit: 1,   color: '#0070bb' },
  { name: 'Full Member',      minActivity: 240,  minMerit: 10,  color: '#0070bb' },
  { name: 'Sr. Member',       minActivity: 480,  minMerit: 100, color: '#0070bb' },
  { name: 'Hero Member',      minActivity: 766,  minMerit: 500, color: '#c7922b' },
  { name: 'Legendary',        minActivity: 1000, minMerit: 999, color: '#c00' },
];

// ── Crypto address regex patterns ───────────────────────────────────────────
export const CRYPTO_PATTERNS = {
  btcLegacy:  /\b(1[a-zA-HJ-NP-Z0-9]{25,34})\b/g,
  btcP2SH:    /\b(3[a-zA-HJ-NP-Z0-9]{25,34})\b/g,
  btcBech32:  /\b(bc1[a-zA-HJ-NP-Z0-9]{6,87})\b/gi,
  eth:        /\b(0x[a-fA-F0-9]{40})\b/g,
  ltc:        /\b(L[a-km-zA-HJ-NP-Z0-9]{26,33})\b/g,
  doge:       /\b(D[5-9A-HJ-NP-U]{1}[1-9A-HJ-NP-Za-km-z]{32})\b/g,
  trx:        /\b(T[1-9A-HJ-NP-Za-km-z]{33})\b/g,
  txid:       /\b([a-fA-F0-9]{64})\b/g,
};

// ── Known phishing/lookalike domains ────────────────────────────────────────
export const SUSPICIOUS_DOMAINS = [
  'bitcointalk.com', 'bitcointaIk.org', 'bitc0intalk.org',
  'blockchaln.com', 'blockchain.co', 'blockchian.com',
  'blokchain.com', 'metamasks.io', 'metarnask.io',
  'binancer.com', 'binancee.com', 'trustwalllet.com',
];

// ── URL shortener domains ────────────────────────────────────────────────────
export const URL_SHORTENERS = [
  'bit.ly', 'tinyurl.com', 't.co', 'goo.gl', 'ow.ly', 'buff.ly',
  'ift.tt', 'dlvr.it', 'is.gd', 'v.gd', 'rb.gy', 'cutt.ly', 'short.io',
];

// ── Module categories ────────────────────────────────────────────────────────
export const MODULE_CATEGORIES = [
  'Posting & BBCode',
  'Thread Tools',
  'Campaign Tools',
  'Security Tools',
  'User/Profile Tools',
  'Layout & Reading',
  'Marketplace Tools',
  'Utility Tools',
  'Legacy Scripts',
];

// ── Block explorer URLs ──────────────────────────────────────────────────────
export const BLOCK_EXPLORERS = {
  btc: [
    { name: 'Blockchain.com', url: 'https://www.blockchain.com/btc/tx/' },
    { name: 'Blockchair',     url: 'https://blockchair.com/bitcoin/transaction/' },
    { name: 'Mempool.space',  url: 'https://mempool.space/tx/' },
  ],
  eth: [
    { name: 'Etherscan', url: 'https://etherscan.io/tx/' },
  ],
};
